version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: command-line-interface
    versions:
    - 4.0.3
  - dependency-name: buntstift
    versions:
    - 4.0.20
    - 4.0.21
  - dependency-name: semantic-release
    versions:
    - 17.3.8
