name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        npm install
    - name: Run tests
      run: |
        npm run test:ci
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
